### ISSUE TITLE
cambio lingua menù

### ISSUE THREAD

**Issue by lopoc** [Metro-Olografix/olografix.org#16]
Quando si cambia lingua dal menù, questo viene chiuso.
Sarebbe carino rimanesse aperto ma con la lingua cambiata.

**Comment by michelangelomo** [comment]
>  Sarebbe carino rimanesse aperto ma con la lingua cambiata.

non credo sia fattibile ora perchè Hugo genera pagine statiche con già i testi nelle varie lingua impostate (es `/it/index.html` e `/en/index.html`). per cambiare lingua senza refresh dovremmo esporre `i18n` su un endpoint e caricare i testi da li con JS
