### ISSUE TITLE
Link preview data (openGraph etc)

### ISSUE THREAD

**Issue by lopoc** [Metro-Olografix/olografix.org#8]
add link preview images, etc.
hugo?

**Comment by michelangelomo** [comment]
https://gohugo.io/templates/embedded/#open-graph 

per ora è fatto a mano: https://github.com/Metro-Olografix/olografix.org/commit/5559ab18390c34d1a2e03976755ba9a6fc61c618#diff-ec6e7cb6e89cbe10d49085811bd67ad23df375247295fc387da90f5fdc56de7fR13
